# Generated by Django 3.2 on 2025-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finova_app', '0002_auto_20250306_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
