# Generated by Django 3.2.25 on 2025-09-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finova_app', '0005_budget_expense_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_budgets', to='finova_app.parentbudget'),
        ),
    ]
