version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: finova
      POSTGRES_USER: finova_user
      POSTGRES_PASSWORD: finova_password

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=finova
      - POSTGRES_USER=finova_user
      - POSTGRES_PASSWORD=finova_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
