export const predefinedCategories = [
    'Food',
    'Transport',
    'Entertainment',
    'Utility Bills',
    'Shopping',
    'Car Insurance',
    'Mobile Phone Bill',
    'Bank Fees',
    'Electricity',
    'House Rent',
    'Petrol',
    'Grocery',
    'Netflix',
    'Karate Classes',
    'Internet Bill',
    'Parking',
    'Healthcare',
    'Education',
    'Subscriptions',
    'Savings & Investments',
    'Loan Payments',
    'Gym Membership',
    'Charity & Donations',
    'Miscellaneous',
    'Water Bill',
    'Gas Bill',
    'Home Maintenance',
    'Vehicle Maintenance',
    'Property Tax',
    'Life Insurance',
    'Health Insurance',
    'Dental Care',
    'Childcare',
    'School Fees',
    'Tuition Fees',
    'Books & Stationery',
    'Streaming Services (Disney+, Prime Video, etc.)',
    'Music Subscriptions (Spotify, Apple Music, etc.)',
    'Cloud Storage (Google Drive, iCloud, etc.)',
    'Software Subscriptions (Adobe, Microsoft 365, etc.)',
    'Emergency Fund',
    'Vacation & Travel',
    'Public Transport (Bus, Train, Metro)',
    'Ride-Sharing (Uber, Lyft, etc.)',
    'Hobbies & Leisure',
    'Dining Out',
    'Fast Food',
    'Pet Expenses',
    'Clothing & Accessories',
    'Beauty & Personal Care',
    'Haircuts & Grooming',
    'Gifts & Celebrations',
    'Home Security Services',
    'Legal Fees',
    'Professional Development (Courses, Certifications)',
    'Investment Fees',
    'Side Business Expenses',
    'Fun & Recreation',
    'Alcohol & Bars',
    'Cigarettes & Vaping',
    'Concerts & Events',
    'Lottery & Gambling',
    // Income-related categories
    'Salary',
    'Freelance Income',
    'Business Income',
    'Investment Income (Dividends, Interest, etc.)',
    'Rental Income',
    'Royalties',
    'Side Hustle Income',
    'Bonuses & Incentives',
    'Commission',
    'Grants & Scholarships',
    'Gifts & Inheritances',
    'Government Benefits (Pensions, Unemployment, etc.)',
    'Tax Refunds',
    'Sale of Assets',
    'Crypto Earnings',
    'Other Income'
];
export const categoryDescriptions = {
    'Food': 'Expenses for groceries, snacks, and meals prepared at home.',
    'Transport': 'Costs for commuting, fuel, and vehicle-related travel.',
    'Entertainment': 'Spending on movies, games, outings, and fun activities.',
    'Utility Bills': 'Monthly bills for electricity, water, gas, Internet and other utilities.',
    'Shopping': 'Purchases of clothes, electronics, and other goods.',
    'Car Insurance': 'Premiums paid for insuring your vehicle.',
    'Mobile Phone Bill': 'Monthly charges for mobile phone services.',
    'Bank Fees': 'Charges from banks for account maintenance or transactions.',
    'Electricity': 'Payments for household electricity usage.',
    'House Rent': 'Monthly rent paid for your residence.',
    'Petrol': 'Fuel expenses for vehicles.',
    'Grocery': 'Spending on food and household essentials.',
    'Netflix': 'Subscription fees for Netflix streaming service.',
    'Karate Classes': 'Fees for attending karate or martial arts classes.',
    'Internet Bill': 'Monthly charges for internet connectivity.',
    'Parking': 'Fees for parking vehicles.',
    'Healthcare': 'Medical expenses, doctor visits, and medicines.',
    'Education': 'Tuition, courses, and educational materials.',
    'Subscriptions': 'Recurring payments for digital or physical services.',
    'Savings & Investments': 'Money set aside or invested for future growth.',
    'Loan Payments': 'Repayments for personal, auto, or home loans.',
    'Gym Membership': 'Fees for gym or fitness club memberships.',
    'Charity & Donations': 'Contributions to charitable organizations.',
    'Miscellaneous': 'Other expenses not categorized elsewhere.',
    'Water Bill': 'Payments for water supply services.',
    'Gas Bill': 'Charges for household gas usage.',
    'Home Maintenance': 'Repairs and upkeep for your home.',
    'Vehicle Maintenance': 'Servicing and repairs for vehicles.',
    'Property Tax': 'Annual taxes paid on owned property.',
    'Life Insurance': 'Premiums for life insurance policies.',
    'Health Insurance': 'Premiums for health insurance coverage.',
    'Dental Care': 'Spending on dental checkups and treatments.',
    'Childcare': 'Costs for daycare, babysitting, or nannies.',
    'School Fees': 'Tuition and fees for school education.',
    'Tuition Fees': 'Payments for higher education or special courses.',
    'Books & Stationery': 'Purchases of books, notebooks, and office supplies.',
    'Streaming Services (Disney+, Prime Video, etc.)': 'Subscriptions to video streaming platforms.',
    'Music Subscriptions (Spotify, Apple Music, etc.)': 'Fees for music streaming services.',
    'Cloud Storage (Google Drive, iCloud, etc.)': 'Payments for online storage solutions.',
    'Software Subscriptions (Adobe, Microsoft 365, etc.)': 'Recurring charges for software tools.',
    'Emergency Fund': 'Money reserved for unexpected expenses.',
    'Vacation & Travel': 'Spending on holidays, trips, and travel bookings.',
    'Public Transport (Bus, Train, Metro)': 'Tickets and passes for public transportation.',
    'Ride-Sharing (Uber, Lyft, etc.)': 'Expenses for ride-hailing services.',
    'Hobbies & Leisure': 'Spending on hobbies, crafts, and leisure activities.',
    'Dining Out': 'Meals and drinks at restaurants and cafes.',
    'Fast Food': 'Quick meals from fast food outlets.',
    'Pet Expenses': 'Costs for pet food, care, and vet visits.',
    'Clothing & Accessories': 'Purchases of apparel and fashion accessories.',
    'Beauty & Personal Care': 'Spending on cosmetics, skincare, and grooming.',
    'Haircuts & Grooming': 'Barber, salon, and grooming services.',
    'Gifts & Celebrations': 'Presents and party expenses for special occasions.',
    'Home Security Services': 'Payments for home security and alarm systems.',
    'Legal Fees': 'Costs for legal advice or services.',
    'Professional Development (Courses, Certifications)': 'Investments in career growth and skills.',
    'Investment Fees': 'Charges for managing investments.',
    'Side Business Expenses': 'Costs related to running a side business.',
    'Fun & Recreation': 'Spending on fun and recreational activities.',
    'Alcohol & Bars': 'Purchases of alcoholic beverages and bar visits.',
    'Cigarettes & Vaping': 'Spending on tobacco and vaping products.',
    'Concerts & Events': 'Tickets for concerts, shows, and events.',
    'Lottery & Gambling': 'Money spent on lottery tickets or gambling.',
    // Income-related categories
    'Salary': 'Regular income from employment.',
    'Freelance Income': 'Earnings from freelance or contract work.',
    'Business Income': 'Profits from business activities.',
    'Investment Income (Dividends, Interest, etc.)': 'Returns from investments and savings.',
    'Rental Income': 'Earnings from renting out property.',
    'Royalties': 'Income from intellectual property or creative works.',
    'Side Hustle Income': 'Extra earnings from side jobs or gigs.',
    'Bonuses & Incentives': 'Additional income from bonuses or rewards.',
    'Commission': 'Earnings based on sales or performance.',
    'Grants & Scholarships': 'Funds received for education or research.',
    'Gifts & Inheritances': 'Money received as gifts or inheritance.',
    'Government Benefits (Pensions, Unemployment, etc.)': 'Support payments from government programs.',
    'Tax Refunds': 'Money returned from tax authorities.',
    'Sale of Assets': 'Income from selling property or items.',
    'Crypto Earnings': 'Profits from cryptocurrency investments.',
    'Other Income': 'Any other sources of income not listed above.'
};